[project]
name = "cocoindex-lancedb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cocoindex>=0.3.22",
    "dspy>=3.0.4",
    "einops>=0.8.1",
    "lancedb>=0.26.0",
    "pillow>=12.0.0",
    "polars>=1.36.1",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
